# Generated by Django 3.0.2 on 2020-02-20 22:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Shopping list name')),
                ('date_added', models.DateTimeField(default=datetime.datetime(2020, 2, 20, 22, 40, 35, 875974, tzinfo=utc))),
                ('is_shared', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_added'],
            },
        ),
        migrations.CreateModel(
            name='ShoppingListItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Product name')),
                ('status', models.BooleanField(default=False, verbose_name='Bought')),
                ('s_list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shoppinglist_manager.ShoppingList')),
            ],
            options={
                'ordering': ['status', 'name'],
            },
        ),
    ]
