# Generated by Django 3.0.2 on 2020-02-15 03:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Shopping list name')),
                ('date_added', models.DateTimeField(default=datetime.datetime(2020, 2, 15, 3, 56, 38, 675368, tzinfo=utc))),
                ('is_shared', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_added'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Task name')),
                ('due_date', models.DateTimeField(default=datetime.datetime(2020, 2, 15, 3, 56, 38, 674652, tzinfo=utc))),
                ('description', models.TextField(max_length=5000)),
                ('status', models.BooleanField(default=False, verbose_name='Done')),
                ('is_shared', models.BooleanField(default=False)),
                ('priority', models.CharField(choices=[('h', 'High'), ('n', 'Normal'), ('l', 'Low')], default='n', max_length=1)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status', 'due_date', 'priority'],
            },
        ),
        migrations.CreateModel(
            name='ShoppingListItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Product name')),
                ('status', models.BooleanField(default=False, verbose_name='Bought')),
                ('s_list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='task_manager.ShoppingList')),
            ],
            options={
                'ordering': ['status', 'name'],
            },
        ),
    ]
