# Generated by Django 3.0.2 on 2020-02-14 11:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0004_auto_20200214_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedShoppingList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Shopping list name')),
                ('date_added', models.DateTimeField(default=datetime.datetime(2020, 2, 14, 11, 27, 39, 518436, tzinfo=utc))),
            ],
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 14, 11, 27, 39, 517369, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 14, 11, 27, 39, 516662, tzinfo=utc)),
        ),
    ]
