# Generated by Django 3.0.2 on 2020-02-14 12:07

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0005_auto_20200214_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedshoppinglist',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 14, 12, 7, 2, 111787, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 14, 12, 7, 2, 110799, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 14, 12, 7, 2, 110080, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='SharedShoppingListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Product name')),
                ('status', models.BooleanField(default=False, verbose_name='Bought')),
                ('s_list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='task_manager.SharedShoppingList')),
            ],
            options={
                'ordering': ['status', 'name'],
            },
        ),
    ]
