# Generated by Django 3.0.2 on 2020-02-14 12:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0006_auto_20200214_1307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharedshoppinglistitem',
            old_name='s_list',
            new_name='ss_list',
        ),
        migrations.AlterField(
            model_name='sharedshoppinglist',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 14, 12, 19, 45, 543451, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 14, 12, 19, 45, 542405, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 14, 12, 19, 45, 541686, tzinfo=utc)),
        ),
    ]
