# Generated by Django 3.0.2 on 2020-02-14 13:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0007_auto_20200214_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharedshoppinglistitem',
            name='ss_list',
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='is_shared',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 14, 13, 6, 41, 483173, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 14, 13, 6, 41, 482432, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='SharedShoppingList',
        ),
        migrations.DeleteModel(
            name='SharedShoppingListItem',
        ),
    ]
