# Generated by Django 3.0.2 on 2020-02-14 13:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0008_auto_20200214_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglist',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 14, 13, 51, 28, 694659, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 14, 13, 51, 28, 693538, tzinfo=utc)),
        ),
    ]
