# Generated by Django 3.0.2 on 2020-02-15 02:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0010_auto_20200215_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglist',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 15, 2, 49, 41, 732328, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 15, 2, 49, 41, 731635, tzinfo=utc)),
        ),
    ]
