# Generated by Django 3.0.2 on 2020-02-15 02:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0011_auto_20200215_0349'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_shared',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 15, 2, 54, 0, 578027, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 15, 2, 54, 0, 577297, tzinfo=utc)),
        ),
    ]
