# Generated by Django 3.0.2 on 2020-02-28 20:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Activity name')),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('time_start', models.TimeField(default=datetime.time(21, 0))),
                ('time_end', models.TimeField(default=datetime.time(23, 0))),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('status_active', models.BooleanField(default=True)),
                ('repeat_weekly', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'time_start', 'status_active'],
            },
        ),
    ]
