# Generated by Django 3.0.2 on 2020-02-25 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='status',
            new_name='status_active',
        ),
        migrations.AddField(
            model_name='activity',
            name='name',
            field=models.CharField(default='bursted', max_length=100),
            preserve_default=False,
        ),
    ]
