# Generated by Django 3.0.2 on 2020-02-26 12:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_manager', '0003_auto_20200226_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='day',
        ),
        migrations.AddField(
            model_name='activity',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='activity',
            name='time_end',
            field=models.TimeField(default=datetime.time(13, 2, 7, 802237)),
        ),
        migrations.AlterField(
            model_name='activity',
            name='time_start',
            field=models.TimeField(default=datetime.time(13, 2, 7, 802209)),
        ),
        migrations.DeleteModel(
            name='ScheduledDay',
        ),
    ]
