# Generated by Django 3.0.2 on 2020-02-26 23:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_manager', '0004_auto_20200226_1302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['date', 'time_start']},
        ),
        migrations.AddField(
            model_name='activity',
            name='description',
            field=models.CharField(default='default', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateField(default='2020-02-27'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='time_end',
            field=models.TimeField(default=datetime.time(0, 48, 9, 555981)),
        ),
        migrations.AlterField(
            model_name='activity',
            name='time_start',
            field=models.TimeField(default=datetime.time(0, 48, 9, 555959)),
        ),
    ]
